# Generated by Django 4.1.6 on 2023-02-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_image_job_imagefun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefun',
            new_name='image',
        ),
    ]
